version: '3.8'

services:
  flask:
    image: alexsuf/flask
    container_name: flask
    stdin_open: true
    tty: true
    environment:
      TZ: Europe/Moscow
    ports:
      - 5000:5000
    command: "python3 /app/app.py"
    volumes:
      - ./app:/app